@startuml
!include <archimate/Archimate>

title IT4IT: Capability Map

Strategy_Capability(e_id9642a3c5a28d5e, "IT4IT: Financial Management")
Strategy_Capability(e_id363de1889d8e59, "IT4IT: Collaboration")
Strategy_Capability(e_id2ed06f8de48b51, "IT4IT: Compliance Management")
Strategy_Capability(e_id34557f35305950, "IT4IT: Contract Management")
Strategy_Capability(e_idc5d385c58e7a50, "IT4IT: Deployment Management")
Strategy_Capability(e_id168009fbbdaf59, "IT4IT: Portfolio Backlog Management")
Strategy_Capability(e_idf5795c282ba359, "IT4IT: Risk Management")
Strategy_Capability(e_idefd285cfa5335f, "IT4IT: Workforce Management")
Grouping(e_id634fb147d1ba56, "IT4IT: Strategy to Portfolio") {
  Strategy_Capability(e_id4d61fa7927b25a, "IT4IT: Architecture Management")
  Strategy_Capability(e_id54b9c32810cf5b, "IT4IT: Customer Relationship Management")
  Strategy_Capability(e_id60efe7ef7f0254, "IT4IT: Demand Management")
  Strategy_Capability(e_id2ef31342d4255f, "IT4IT: Policy Management")
  Strategy_Capability(e_idb1a0af63d8cb5a, "IT4IT: Product Portfolio Management")
  Strategy_Capability(e_id30f3cad2646751, "IT4IT: Strategy Management")
}
Grouping(e_id4407e2df936d5a, "IT4IT: Requirement to Deploy") {
  Strategy_Capability(e_id8b40f1ce15d35f, "IT4IT: Defect Management")
  Strategy_Capability(e_idbfbff7c159ea5f, "IT4IT: Product Backlog Management")
  Strategy_Capability(e_ideeaf0949683a5c, "IT4IT: Product Design Management")
  Strategy_Capability(e_idd778fc8624cb59, "IT4IT: Product Development")
  Strategy_Capability(e_idc2df3e389ec759, "IT4IT: Release Management")
  Strategy_Capability(e_idd6ac415340a950, "IT4IT: Requirements Management")
  Strategy_Capability(e_idab8c06ee6b0756, "IT4IT: Test Management")
}
Grouping(e_id736e56c348d85b, "IT4IT: Request to Fulfill") {
  Strategy_Capability(e_id5219b08cf00655, "IT4IT: Asset Management")
  Strategy_Capability(e_ided9194c5cf9059, "IT4IT: Customer/User Support")
  Strategy_Capability(e_id32ee3b308e0755, "IT4IT: Procurement Management")
  Strategy_Capability(e_idf6987f39696952, "IT4IT: Product Sales Management")
  Strategy_Capability(e_idc8adb7317fb55b, "IT4IT: Request Management")
  Strategy_Capability(e_id0a1d3ebdece256, "IT4IT: Service Catalog Management")
  Strategy_Capability(e_id51eb1829b92c5c, "IT4IT: Vendor Management")
}
Grouping(e_id29ed566be79e5d, "IT4IT: Detect to Correct") {
  Strategy_Capability(e_id7b19e8d35c4357, "IT4IT: Availability Management")
  Strategy_Capability(e_id01e6afec5ed95d, "IT4IT: Capacity Management")
  Strategy_Capability(e_id84098be1d6b45f, "IT4IT: Change Management")
  Strategy_Capability(e_ided0fa997568f53, "IT4IT: Configuration Management")
  Strategy_Capability(e_id23d1ff6a8a8755, "IT4IT: Continuity Management")
  Strategy_Capability(e_ide2e18c38b01752, "IT4IT: Event Management")
  Strategy_Capability(e_idc7533f43467952, "IT4IT: Identity and Access Management")
  Strategy_Capability(e_idea7c98f367cf57, "IT4IT: Incident Management")
  Strategy_Capability(e_id9ad1b6abdd4353, "IT4IT: Knowledge Management")
  Strategy_Capability(e_ide974342a0d7d53, "IT4IT: Measurement & Reporting")
  Strategy_Capability(e_id844973bed03656, "IT4IT: Operations Management")
  Strategy_Capability(e_id2366c163d8015a, "IT4IT: Performance Management")
  Strategy_Capability(e_id7cf2274305e256, "IT4IT: Problem Management")
  Strategy_Capability(e_idd44566c9effd57, "IT4IT: Service Level Management")
}


@enduml
