@startuml
!include <archimate/Archimate>

title IT4IT Alignment

Strategy_ValueStream(e_idf2e1bcaab0b050, "IT4IT: Value Streams") {
  Strategy_ValueStream(e_id7fb8e4a3ead059, "IT4IT: Explore") {
    Strategy_ValueStream(e_idb26c47d4351d5f, "Explore: Define Digital Product Architecture")
    Strategy_ValueStream(e_ideb6f10a6249856, "Explore: Refine Product Backlog")
    Strategy_ValueStream(e_id3cce6ddd71a554, "Explore: Prioritize Backlog Items")
    Strategy_ValueStream(e_id5fc8f94282b356, "Explore: Finalize Roadmap & Scope Agreement")
  }
  Strategy_ValueStream(e_id587fca1cae9254, "IT4IT: Evaluate") {
    Strategy_ValueStream(e_idecf3aeb9893450, "Evaluate: Gather Influencers")
    Strategy_ValueStream(e_id203cb4d955ba5f, "Evaluate: Define Backlog Mandates")
    Strategy_ValueStream(e_id98e23fd095a153, "Evaluate: Ensure Governance")
    Strategy_ValueStream(e_id06281c147bed57, "Evaluate: Identify Gaps")
    Strategy_ValueStream(e_idf47d7e3978f95d, "Evaluate: Propose Investments")
  }
  Strategy_ValueStream(e_id3db0cbb3835a52, "IT4IT: Integrate") {
    Strategy_ValueStream(e_id05a09249ecd25e, "Integrate: Plan Product Release")
    Strategy_ValueStream(e_id4d232b4e4d9151, "Integrate: Design & Develop")
    Strategy_ValueStream(e_id0925fc6db80453, "Integrate: Build, Integrate, & Test")
    Strategy_ValueStream(e_id6e0b4917897f59, "Integrate: Accept & Publish Release")
  }
  Strategy_ValueStream(e_id2a9a1fcfef0e5f, "IT4IT: Deploy") {
    Strategy_ValueStream(e_id8a5fa5c4e9f35c, "Deploy: Plan & Approve Deployment")
    Strategy_ValueStream(e_id409cff1ce21453, "Deploy: Fulfill Deployment")
    Strategy_ValueStream(e_id890c954b99ef59, "Deploy: Observe Deployment")
    Strategy_ValueStream(e_id633614d2551b5e, "Deploy: Validate Deployment")
  }
  Strategy_ValueStream(e_id2450fe8b5d985b, "IT4IT: Release") {
    Strategy_ValueStream(e_id43cdfeb06e1b53, "Release: Define Service Offer")
    Strategy_ValueStream(e_idda5e39c5b86f5f, "Release: Implement Service Offer")
    Strategy_ValueStream(e_id7325bf4931935a, "Release: Publish Service Offer")
  }
  Strategy_ValueStream(e_idd9aa16f51da958, "IT4IT: Operate") {
    Strategy_ValueStream(e_id61e6c145346959, "Operate: Detect Issue")
    Strategy_ValueStream(e_id7fed31beba0b52, "Operate: Diagnose Issue")
    Strategy_ValueStream(e_id983000175eba5f, "Operate: Resolve Issue")
  }
  Strategy_ValueStream(e_idd3ec795635fd51, "IT4IT: Consume") {
    Strategy_ValueStream(e_id6034216de9d457, "Consume: Publish Service Status")
    Strategy_ValueStream(e_id960e39e570c95b, "Consume: Provide Service Support")
    Strategy_ValueStream(e_idb1e9e123fa665a, "Consume: Agree to Service Offer")
    Strategy_ValueStream(e_id651f82429d3d53, "Consume: Subscribe to Service Offer")
    Strategy_ValueStream(e_id447d4f6179dc5e, "Consume: Select an Offer")
  }
}
Motivation_Outcome(e_id98a0748d593250, "IT4IT: Digital Product")
Strategy_Capability(e_id4d61fa7927b25a, "IT4IT: Architecture Management")
Strategy_Capability(e_id5219b08cf00655, "IT4IT: Asset Management")
Strategy_Capability(e_ided0fa997568f53, "IT4IT: Configuration Management")
Strategy_Capability(e_id8b40f1ce15d35f, "IT4IT: Defect Management")
Strategy_Capability(e_id60efe7ef7f0254, "IT4IT: Demand Management")
Strategy_Capability(e_ide2e18c38b01752, "IT4IT: Event Management")
Strategy_Capability(e_id9642a3c5a28d5e, "IT4IT: Financial Management")
Strategy_Capability(e_idea7c98f367cf57, "IT4IT: Incident Management")
Strategy_Capability(e_ide974342a0d7d53, "IT4IT: Measurement & Reporting")
Strategy_Capability(e_id844973bed03656, "IT4IT: Operations Management")
Strategy_Capability(e_id2ef31342d4255f, "IT4IT: Policy Management")
Strategy_Capability(e_id7cf2274305e256, "IT4IT: Problem Management")
Strategy_Capability(e_id32ee3b308e0755, "IT4IT: Procurement Management")
Strategy_Capability(e_idbfbff7c159ea5f, "IT4IT: Product Backlog Management")
Strategy_Capability(e_ideeaf0949683a5c, "IT4IT: Product Design Management")
Strategy_Capability(e_idd778fc8624cb59, "IT4IT: Product Development")
Strategy_Capability(e_idb1a0af63d8cb5a, "IT4IT: Product Portfolio Management")
Strategy_Capability(e_idc2df3e389ec759, "IT4IT: Release Management")
Strategy_Capability(e_idc8adb7317fb55b, "IT4IT: Request Management")
Strategy_Capability(e_idd6ac415340a950, "IT4IT: Requirements Management")
Strategy_Capability(e_id0a1d3ebdece256, "IT4IT: Service Catalog Management")
Strategy_Capability(e_idd44566c9effd57, "IT4IT: Service Level Management")
Strategy_Capability(e_idab8c06ee6b0756, "IT4IT: Test Management")
Strategy_Capability(e_id51eb1829b92c5c, "IT4IT: Vendor Management")
Strategy_Capability(e_id7b19e8d35c4357, "IT4IT: Availability Management")
Strategy_Capability(e_id01e6afec5ed95d, "IT4IT: Capacity Management")
Strategy_Capability(e_id84098be1d6b45f, "IT4IT: Change Management")
Strategy_Capability(e_id363de1889d8e59, "IT4IT: Collaboration")
Strategy_Capability(e_id2ed06f8de48b51, "IT4IT: Compliance Management")
Strategy_Capability(e_id23d1ff6a8a8755, "IT4IT: Continuity Management")
Strategy_Capability(e_id34557f35305950, "IT4IT: Contract Management")
Strategy_Capability(e_id54b9c32810cf5b, "IT4IT: Customer Relationship Management")
Strategy_Capability(e_ided9194c5cf9059, "IT4IT: Customer/User Support")
Strategy_Capability(e_idc5d385c58e7a50, "IT4IT: Deployment Management")
Strategy_Capability(e_idc7533f43467952, "IT4IT: Identity and Access Management")
Strategy_Capability(e_id9ad1b6abdd4353, "IT4IT: Knowledge Management")
Strategy_Capability(e_id2366c163d8015a, "IT4IT: Performance Management")
Strategy_Capability(e_id168009fbbdaf59, "IT4IT: Portfolio Backlog Management")
Strategy_Capability(e_idf6987f39696952, "IT4IT: Product Sales Management")
Strategy_Capability(e_idf5795c282ba359, "IT4IT: Risk Management")
Strategy_Capability(e_id30f3cad2646751, "IT4IT: Strategy Management")
Strategy_Capability(e_idefd285cfa5335f, "IT4IT: Workforce Management")

Rel_Realization_Up(e_idf2e1bcaab0b050, e_id98a0748d593250, "")
Rel_Flow_Right(e_id2450fe8b5d985b, e_idd3ec795635fd51, "")
Rel_Flow_Right(e_id2a9a1fcfef0e5f, e_id587fca1cae9254, "")
Rel_Flow_Right(e_idd3ec795635fd51, e_id587fca1cae9254, "")
Rel_Flow_Right(e_id7fb8e4a3ead059, e_id3db0cbb3835a52, "")
Rel_Flow_Right(e_id587fca1cae9254, e_idd3ec795635fd51, "")
Rel_Flow_Right(e_id587fca1cae9254, e_id7fb8e4a3ead059, "")
Rel_Flow_Right(e_id587fca1cae9254, e_idd9aa16f51da958, "")
Rel_Flow_Right(e_idd9aa16f51da958, e_id587fca1cae9254, "")
Rel_Flow_Right(e_id2a9a1fcfef0e5f, e_idd9aa16f51da958, "")
Rel_Flow_Right(e_idd3ec795635fd51, e_idd9aa16f51da958, "")
Rel_Flow_Right(e_id3db0cbb3835a52, e_id2a9a1fcfef0e5f, "")
Rel_Flow_Right(e_id587fca1cae9254, e_id2450fe8b5d985b, "")
Rel_Flow_Right(e_id2450fe8b5d985b, e_id587fca1cae9254, "")
Rel_Flow_Right(e_id587fca1cae9254, e_id3db0cbb3835a52, "")
Rel_Flow_Right(e_id3db0cbb3835a52, e_id2450fe8b5d985b, "")
Rel_Flow_Right(e_id7fb8e4a3ead059, e_id587fca1cae9254, "")
Rel_Flow_Right(e_id3db0cbb3835a52, e_id587fca1cae9254, "")
Rel_Flow_Right(e_id587fca1cae9254, e_id2a9a1fcfef0e5f, "")
Rel_Serving_Up(e_idc8adb7317fb55b, e_idb1e9e123fa665a, "<<derived>>")
Rel_Serving_Up(e_idd44566c9effd57, e_idb1e9e123fa665a, "<<derived>>")
Rel_Serving_Up(e_id9642a3c5a28d5e, e_id6034216de9d457, "<<derived>>")
Rel_Serving_Up(e_idea7c98f367cf57, e_id6034216de9d457, "<<derived>>")
Rel_Serving_Up(e_id32ee3b308e0755, e_id6034216de9d457, "<<derived>>")
Rel_Serving_Up(e_idc8adb7317fb55b, e_id6034216de9d457, "<<derived>>")
Rel_Serving_Up(e_idd44566c9effd57, e_id6034216de9d457, "<<derived>>")
Rel_Serving_Up(e_id51eb1829b92c5c, e_id6034216de9d457, "<<derived>>")
Rel_Serving_Up(e_idc8adb7317fb55b, e_id447d4f6179dc5e, "<<derived>>")
Rel_Serving_Up(e_id0a1d3ebdece256, e_id447d4f6179dc5e, "<<derived>>")
Rel_Serving_Up(e_id5219b08cf00655, e_id651f82429d3d53, "<<derived>>")
Rel_Serving_Up(e_ided0fa997568f53, e_id651f82429d3d53, "<<derived>>")
Rel_Serving_Up(e_id9642a3c5a28d5e, e_id651f82429d3d53, "<<derived>>")
Rel_Serving_Up(e_id32ee3b308e0755, e_id651f82429d3d53, "<<derived>>")
Rel_Serving_Up(e_idc8adb7317fb55b, e_id651f82429d3d53, "<<derived>>")
Rel_Serving_Up(e_idd44566c9effd57, e_id651f82429d3d53, "<<derived>>")
Rel_Serving_Up(e_id51eb1829b92c5c, e_id651f82429d3d53, "<<derived>>")
Rel_Serving_Up(e_idea7c98f367cf57, e_id960e39e570c95b, "<<derived>>")
Rel_Serving_Up(e_idc8adb7317fb55b, e_id960e39e570c95b, "<<derived>>")
Rel_Serving_Up(e_id5219b08cf00655, e_id409cff1ce21453, "<<derived>>")
Rel_Serving_Up(e_ided0fa997568f53, e_id409cff1ce21453, "<<derived>>")
Rel_Serving_Up(e_ide974342a0d7d53, e_id409cff1ce21453, "<<derived>>")
Rel_Serving_Up(e_id844973bed03656, e_id409cff1ce21453, "<<derived>>")
Rel_Serving_Up(e_id7cf2274305e256, e_id409cff1ce21453, "<<derived>>")
Rel_Serving_Up(e_id32ee3b308e0755, e_id409cff1ce21453, "<<derived>>")
Rel_Serving_Up(e_idc2df3e389ec759, e_id409cff1ce21453, "<<derived>>")
Rel_Serving_Up(e_idc8adb7317fb55b, e_id409cff1ce21453, "<<derived>>")
Rel_Serving_Up(e_ided0fa997568f53, e_id8a5fa5c4e9f35c, "<<derived>>")
Rel_Serving_Up(e_id32ee3b308e0755, e_id8a5fa5c4e9f35c, "<<derived>>")
Rel_Serving_Up(e_idc2df3e389ec759, e_id8a5fa5c4e9f35c, "<<derived>>")
Rel_Serving_Up(e_idc8adb7317fb55b, e_id8a5fa5c4e9f35c, "<<derived>>")
Rel_Serving_Up(e_idd44566c9effd57, e_id8a5fa5c4e9f35c, "<<derived>>")
Rel_Serving_Up(e_id5219b08cf00655, e_id633614d2551b5e, "<<derived>>")
Rel_Serving_Up(e_ided0fa997568f53, e_id633614d2551b5e, "<<derived>>")
Rel_Serving_Up(e_id844973bed03656, e_id633614d2551b5e, "<<derived>>")
Rel_Serving_Up(e_id7cf2274305e256, e_id633614d2551b5e, "<<derived>>")
Rel_Serving_Up(e_id32ee3b308e0755, e_id633614d2551b5e, "<<derived>>")
Rel_Serving_Up(e_idc2df3e389ec759, e_id633614d2551b5e, "<<derived>>")
Rel_Serving_Up(e_idc8adb7317fb55b, e_id633614d2551b5e, "<<derived>>")
Rel_Serving_Up(e_idd44566c9effd57, e_id633614d2551b5e, "<<derived>>")
Rel_Serving_Up(e_id4d61fa7927b25a, e_id203cb4d955ba5f, "<<derived>>")
Rel_Serving_Up(e_id60efe7ef7f0254, e_id203cb4d955ba5f, "<<derived>>")
Rel_Serving_Up(e_id2ef31342d4255f, e_id203cb4d955ba5f, "<<derived>>")
Rel_Serving_Up(e_idb1a0af63d8cb5a, e_id203cb4d955ba5f, "<<derived>>")
Rel_Serving_Up(e_id4d61fa7927b25a, e_idecf3aeb9893450, "<<derived>>")
Rel_Serving_Up(e_id60efe7ef7f0254, e_idecf3aeb9893450, "<<derived>>")
Rel_Serving_Up(e_id2ef31342d4255f, e_idecf3aeb9893450, "<<derived>>")
Rel_Serving_Up(e_idb1a0af63d8cb5a, e_idecf3aeb9893450, "<<derived>>")
Rel_Serving_Up(e_id4d61fa7927b25a, e_idf47d7e3978f95d, "<<derived>>")
Rel_Serving_Up(e_id60efe7ef7f0254, e_idf47d7e3978f95d, "<<derived>>")
Rel_Serving_Up(e_id2ef31342d4255f, e_idf47d7e3978f95d, "<<derived>>")
Rel_Serving_Up(e_idb1a0af63d8cb5a, e_idf47d7e3978f95d, "<<derived>>")
Rel_Serving_Up(e_id4d61fa7927b25a, e_id3cce6ddd71a554, "<<derived>>")
Rel_Serving_Up(e_id60efe7ef7f0254, e_id3cce6ddd71a554, "<<derived>>")
Rel_Serving_Up(e_id2ef31342d4255f, e_id3cce6ddd71a554, "<<derived>>")
Rel_Serving_Up(e_ideeaf0949683a5c, e_id3cce6ddd71a554, "<<derived>>")
Rel_Serving_Up(e_idb1a0af63d8cb5a, e_id3cce6ddd71a554, "<<derived>>")
Rel_Serving_Up(e_idd6ac415340a950, e_id3cce6ddd71a554, "<<derived>>")
Rel_Serving_Up(e_id60efe7ef7f0254, e_ideb6f10a6249856, "<<derived>>")
Rel_Serving_Up(e_id2ef31342d4255f, e_ideb6f10a6249856, "<<derived>>")
Rel_Serving_Up(e_idbfbff7c159ea5f, e_ideb6f10a6249856, "<<derived>>")
Rel_Serving_Up(e_ideeaf0949683a5c, e_ideb6f10a6249856, "<<derived>>")
Rel_Serving_Up(e_idb1a0af63d8cb5a, e_ideb6f10a6249856, "<<derived>>")
Rel_Serving_Up(e_idd6ac415340a950, e_ideb6f10a6249856, "<<derived>>")
Rel_Serving_Up(e_id60efe7ef7f0254, e_id5fc8f94282b356, "<<derived>>")
Rel_Serving_Up(e_id9642a3c5a28d5e, e_id5fc8f94282b356, "<<derived>>")
Rel_Serving_Up(e_id2ef31342d4255f, e_id5fc8f94282b356, "<<derived>>")
Rel_Serving_Up(e_idbfbff7c159ea5f, e_id5fc8f94282b356, "<<derived>>")
Rel_Serving_Up(e_ideeaf0949683a5c, e_id5fc8f94282b356, "<<derived>>")
Rel_Serving_Up(e_idb1a0af63d8cb5a, e_id5fc8f94282b356, "<<derived>>")
Rel_Serving_Up(e_id8b40f1ce15d35f, e_id6e0b4917897f59, "<<derived>>")
Rel_Serving_Up(e_id32ee3b308e0755, e_id6e0b4917897f59, "<<derived>>")
Rel_Serving_Up(e_idbfbff7c159ea5f, e_id6e0b4917897f59, "<<derived>>")
Rel_Serving_Up(e_idc2df3e389ec759, e_id6e0b4917897f59, "<<derived>>")
Rel_Serving_Up(e_idc8adb7317fb55b, e_id6e0b4917897f59, "<<derived>>")
Rel_Serving_Up(e_idd6ac415340a950, e_id6e0b4917897f59, "<<derived>>")
Rel_Serving_Up(e_idab8c06ee6b0756, e_id6e0b4917897f59, "<<derived>>")
Rel_Serving_Up(e_idd778fc8624cb59, e_id0925fc6db80453, "<<derived>>")
Rel_Serving_Up(e_idc2df3e389ec759, e_id0925fc6db80453, "<<derived>>")
Rel_Serving_Up(e_id8b40f1ce15d35f, e_id4d232b4e4d9151, "<<derived>>")
Rel_Serving_Up(e_idbfbff7c159ea5f, e_id4d232b4e4d9151, "<<derived>>")
Rel_Serving_Up(e_ideeaf0949683a5c, e_id4d232b4e4d9151, "<<derived>>")
Rel_Serving_Up(e_idd778fc8624cb59, e_id4d232b4e4d9151, "<<derived>>")
Rel_Serving_Up(e_idc8adb7317fb55b, e_id4d232b4e4d9151, "<<derived>>")
Rel_Serving_Up(e_idd6ac415340a950, e_id4d232b4e4d9151, "<<derived>>")
Rel_Serving_Up(e_idab8c06ee6b0756, e_id4d232b4e4d9151, "<<derived>>")
Rel_Serving_Up(e_idbfbff7c159ea5f, e_id05a09249ecd25e, "<<derived>>")
Rel_Serving_Up(e_idd6ac415340a950, e_id05a09249ecd25e, "<<derived>>")
Rel_Serving_Up(e_idab8c06ee6b0756, e_id05a09249ecd25e, "<<derived>>")
Rel_Serving_Up(e_ided0fa997568f53, e_id61e6c145346959, "<<derived>>")
Rel_Serving_Up(e_ide2e18c38b01752, e_id61e6c145346959, "<<derived>>")
Rel_Serving_Up(e_idea7c98f367cf57, e_id61e6c145346959, "<<derived>>")
Rel_Serving_Up(e_ide974342a0d7d53, e_id61e6c145346959, "<<derived>>")
Rel_Serving_Up(e_idc8adb7317fb55b, e_id61e6c145346959, "<<derived>>")
Rel_Serving_Up(e_idd44566c9effd57, e_id61e6c145346959, "<<derived>>")
Rel_Serving_Up(e_ided0fa997568f53, e_id7fed31beba0b52, "<<derived>>")
Rel_Serving_Up(e_ide2e18c38b01752, e_id7fed31beba0b52, "<<derived>>")
Rel_Serving_Up(e_idea7c98f367cf57, e_id7fed31beba0b52, "<<derived>>")
Rel_Serving_Up(e_id844973bed03656, e_id7fed31beba0b52, "<<derived>>")
Rel_Serving_Up(e_id7cf2274305e256, e_id7fed31beba0b52, "<<derived>>")
Rel_Serving_Up(e_idd44566c9effd57, e_id7fed31beba0b52, "<<derived>>")
Rel_Serving_Up(e_ided0fa997568f53, e_id983000175eba5f, "<<derived>>")
Rel_Serving_Up(e_ide2e18c38b01752, e_id983000175eba5f, "<<derived>>")
Rel_Serving_Up(e_idea7c98f367cf57, e_id983000175eba5f, "<<derived>>")
Rel_Serving_Up(e_id844973bed03656, e_id983000175eba5f, "<<derived>>")
Rel_Serving_Up(e_idc8adb7317fb55b, e_id983000175eba5f, "<<derived>>")
Rel_Serving_Up(e_idd44566c9effd57, e_id983000175eba5f, "<<derived>>")
Rel_Serving_Up(e_idc2df3e389ec759, e_id43cdfeb06e1b53, "<<derived>>")
Rel_Serving_Up(e_id0a1d3ebdece256, e_id43cdfeb06e1b53, "<<derived>>")
Rel_Serving_Up(e_idd44566c9effd57, e_id43cdfeb06e1b53, "<<derived>>")
Rel_Serving_Up(e_id0a1d3ebdece256, e_idda5e39c5b86f5f, "<<derived>>")
Rel_Serving_Up(e_id0a1d3ebdece256, e_id7325bf4931935a, "<<derived>>")

@enduml
