@startuml
!include <archimate/Archimate>

title IT4IT: Outcome Realization

Strategy_ValueStream(e_idf2e1bcaab0b050, "IT4IT: Value Streams") {
  Strategy_ValueStream(e_id7fb8e4a3ead059, "IT4IT: Explore")
  Strategy_ValueStream(e_id587fca1cae9254, "IT4IT: Evaluate")
  Strategy_ValueStream(e_id3db0cbb3835a52, "IT4IT: Integrate")
  Strategy_ValueStream(e_id2a9a1fcfef0e5f, "IT4IT: Deploy")
  Strategy_ValueStream(e_id2450fe8b5d985b, "IT4IT: Release")
  Strategy_ValueStream(e_idd9aa16f51da958, "IT4IT: Operate")
  Strategy_ValueStream(e_idd3ec795635fd51, "IT4IT: Consume")
}
Motivation_Outcome(e_id98a0748d593250, "IT4IT: Digital Product")
Motivation_Outcome(e_id7a9aadc56b6458, "IT4IT: Investigate a New Digital Product Idea")
Motivation_Outcome(e_id16c97079bdba5c, "IT4IT: Retire Digital Product")
Motivation_Outcome(e_id6f88e224dfda51, "IT4IT: Digital Product Vision, Design, and Product Roadmap")
Motivation_Outcome(e_id5196d288af7b59, "IT4IT: Optimize a Digital Product")
Motivation_Outcome(e_id57c03dbe6b7251, "IT4IT: Refine Digital Product Feasibility")
Motivation_Outcome(e_id78beaa69dce05f, "IT4IT: Rationalize the Product Portfolio")
Motivation_Outcome(e_id0308dd03038555, "IT4IT: Plan Product Portfolio Investments")
Motivation_Outcome(e_id1601a664772252, "IT4IT: Perform Digital Product Governance")
Motivation_Outcome(e_idbd6c2c74a8505f, "IT4IT: Consider a New Digital Product")
Motivation_Outcome(e_idf4277ae2dd6851, "IT4IT: Prioritized Digital Product Portfolio and Architecture Roadmap")
Motivation_Outcome(e_id4417fb4770d85c, "IT4IT: Configure an Off-the-Shelf or SaaS Product for Use")
Motivation_Outcome(e_idadb8e64088f053, "IT4IT: Develop a New or Initial Product Release")
Motivation_Outcome(e_id43225b4f2ab05d, "IT4IT: Update of a Vendor Product")
Motivation_Outcome(e_id7ae71bd160375f, "IT4IT: New Product Release")
Motivation_Outcome(e_ide56c29e2893252, "IT4IT: Deliver an Emergency Change or Hotfix")
Motivation_Outcome(e_idcdaf0f96f3ae55, "IT4IT: Consumable Product Instance")
Motivation_Outcome(e_id00490e375a8b51, "IT4IT: Deploy a New Product Release Version for a Digital Product")
Motivation_Outcome(e_id3c3c228a78365c, "IT4IT: Deploy a First Product Release for a New Digital Product")
Motivation_Outcome(e_id9b90f93a29145a, "IT4IT: Disable or Remove Existing Product Release Instances of a Digital Product")
Motivation_Outcome(e_ida09d1eb1e2095c, "IT4IT: Terminate a Service Offer")
Motivation_Outcome(e_id8d4279addae053, "IT4IT: Bundle Existing Service Offers")
Motivation_Outcome(e_idc9385eb3138c59, "IT4IT: Orderable Service Offer(s)")
Motivation_Outcome(e_id4cc246de7aab5f, "IT4IT: Release a New Service Offer")
Motivation_Outcome(e_id14e29033591d54, "IT4IT: Change an Existing Service Offer")
Motivation_Outcome(e_id56da162d16715b, "IT4IT: Ensure Disaster Recovery Objectives")
Motivation_Outcome(e_ide0cb6af92aa05c, "IT4IT: Remediate Consumer Front-End Issue")
Motivation_Outcome(e_id6a4877aa385f5f, "IT4IT: Perform Scheduled Maintenance")
Motivation_Outcome(e_ide3d3fa75957654, "IT4IT: Actual Product operated according to or exceeding expectation")
Motivation_Outcome(e_idf2bf537472d451, "IT4IT: Remediate a major Event or Incident")
Motivation_Outcome(e_id3ee2475f387f56, "IT4IT: Remediate an Identified Back-End Issue")
Motivation_Outcome(e_id7bc7cff2bb5f54, "IT4IT: Order an Actual Product Instance Modification")
Motivation_Outcome(e_id603848d3e4045a, "IT4IT: Order a New Desired Product Instance")
Motivation_Outcome(e_idb647f741bf2d52, "IT4IT: Order an Actual Product Instance Support")
Motivation_Outcome(e_id3fec15b8d37855, "IT4IT: Order an Actual Product Instance Termination")
Motivation_Outcome(e_idba59916d532351, "IT4IT: Service Subscription")

Rel_Realization_Up(e_idf2e1bcaab0b050, e_id98a0748d593250, "")
Rel_Flow(e_id2450fe8b5d985b, e_idd3ec795635fd51, "")
Rel_Flow(e_id2a9a1fcfef0e5f, e_id587fca1cae9254, "")
Rel_Flow(e_idd3ec795635fd51, e_id587fca1cae9254, "")
Rel_Flow(e_id7fb8e4a3ead059, e_id3db0cbb3835a52, "")
Rel_Flow(e_id587fca1cae9254, e_idd3ec795635fd51, "")
Rel_Flow(e_id587fca1cae9254, e_id7fb8e4a3ead059, "")
Rel_Flow(e_id587fca1cae9254, e_idd9aa16f51da958, "")
Rel_Flow(e_idd9aa16f51da958, e_id587fca1cae9254, "")
Rel_Flow(e_id2a9a1fcfef0e5f, e_idd9aa16f51da958, "")
Rel_Flow(e_idd3ec795635fd51, e_idd9aa16f51da958, "")
Rel_Flow(e_id3db0cbb3835a52, e_id2a9a1fcfef0e5f, "")
Rel_Flow(e_id587fca1cae9254, e_id2450fe8b5d985b, "")
Rel_Flow(e_id2450fe8b5d985b, e_id587fca1cae9254, "")
Rel_Flow(e_id587fca1cae9254, e_id3db0cbb3835a52, "")
Rel_Flow(e_id3db0cbb3835a52, e_id2450fe8b5d985b, "")
Rel_Flow(e_id7fb8e4a3ead059, e_id587fca1cae9254, "")
Rel_Flow(e_id3db0cbb3835a52, e_id587fca1cae9254, "")
Rel_Flow(e_id587fca1cae9254, e_id2a9a1fcfef0e5f, "")
Rel_Realization_Up(e_id7fb8e4a3ead059, e_id7a9aadc56b6458, "")
Rel_Realization_Up(e_id7fb8e4a3ead059, e_id16c97079bdba5c, "")
Rel_Realization_Up(e_id7fb8e4a3ead059, e_id6f88e224dfda51, "")
Rel_Realization_Up(e_id7fb8e4a3ead059, e_id5196d288af7b59, "")
Rel_Realization_Up(e_id7fb8e4a3ead059, e_id57c03dbe6b7251, "")
Rel_Realization_Up(e_id587fca1cae9254, e_id78beaa69dce05f, "")
Rel_Realization_Up(e_id587fca1cae9254, e_id0308dd03038555, "")
Rel_Realization_Up(e_id587fca1cae9254, e_id1601a664772252, "")
Rel_Realization_Up(e_id587fca1cae9254, e_idbd6c2c74a8505f, "")
Rel_Realization_Up(e_id587fca1cae9254, e_idf4277ae2dd6851, "")
Rel_Realization_Up(e_id3db0cbb3835a52, e_id4417fb4770d85c, "")
Rel_Realization_Up(e_id3db0cbb3835a52, e_idadb8e64088f053, "")
Rel_Realization_Up(e_id3db0cbb3835a52, e_id43225b4f2ab05d, "")
Rel_Realization_Up(e_id3db0cbb3835a52, e_id7ae71bd160375f, "")
Rel_Realization_Up(e_id3db0cbb3835a52, e_ide56c29e2893252, "")
Rel_Realization_Up(e_id2a9a1fcfef0e5f, e_idcdaf0f96f3ae55, "")
Rel_Realization_Up(e_id2a9a1fcfef0e5f, e_id00490e375a8b51, "")
Rel_Realization_Up(e_id2a9a1fcfef0e5f, e_id3c3c228a78365c, "")
Rel_Realization_Up(e_id2a9a1fcfef0e5f, e_id9b90f93a29145a, "")
Rel_Realization_Up(e_id2450fe8b5d985b, e_ida09d1eb1e2095c, "")
Rel_Realization_Up(e_id2450fe8b5d985b, e_id8d4279addae053, "")
Rel_Realization_Up(e_id2450fe8b5d985b, e_idc9385eb3138c59, "")
Rel_Realization_Up(e_id2450fe8b5d985b, e_id4cc246de7aab5f, "")
Rel_Realization_Up(e_id2450fe8b5d985b, e_id14e29033591d54, "")
Rel_Realization_Up(e_idd9aa16f51da958, e_id56da162d16715b, "")
Rel_Realization_Up(e_idd9aa16f51da958, e_ide0cb6af92aa05c, "")
Rel_Realization_Up(e_idd9aa16f51da958, e_id6a4877aa385f5f, "")
Rel_Realization_Up(e_idd9aa16f51da958, e_ide3d3fa75957654, "")
Rel_Realization_Up(e_idd9aa16f51da958, e_idf2bf537472d451, "")
Rel_Realization_Up(e_idd9aa16f51da958, e_id3ee2475f387f56, "")
Rel_Realization_Up(e_idd3ec795635fd51, e_id7bc7cff2bb5f54, "")
Rel_Realization_Up(e_idd3ec795635fd51, e_id603848d3e4045a, "")
Rel_Realization_Up(e_idd3ec795635fd51, e_idb647f741bf2d52, "")
Rel_Realization_Up(e_idd3ec795635fd51, e_id3fec15b8d37855, "")
Rel_Realization_Up(e_idd3ec795635fd51, e_idba59916d532351, "")

@enduml
