@startuml
!include <archimate/Archimate>

title IT4IT: Value Streams

Strategy_ValueStream(e_idf2e1bcaab0b050, "IT4IT: Value Streams") {
  Strategy_ValueStream(e_id7fb8e4a3ead059, "IT4IT: Explore") {
    Strategy_ValueStream(e_idb26c47d4351d5f, "Explore: Define Digital Product Architecture")
    Strategy_ValueStream(e_ideb6f10a6249856, "Explore: Refine Product Backlog")
    Strategy_ValueStream(e_id3cce6ddd71a554, "Explore: Prioritize Backlog Items")
    Strategy_ValueStream(e_id5fc8f94282b356, "Explore: Finalize Roadmap & Scope Agreement")
  }
  Strategy_ValueStream(e_id587fca1cae9254, "IT4IT: Evaluate") {
    Strategy_ValueStream(e_idecf3aeb9893450, "Evaluate: Gather Influencers")
    Strategy_ValueStream(e_id203cb4d955ba5f, "Evaluate: Define Backlog Mandates")
    Strategy_ValueStream(e_id98e23fd095a153, "Evaluate: Ensure Governance")
    Strategy_ValueStream(e_id06281c147bed57, "Evaluate: Identify Gaps")
    Strategy_ValueStream(e_idf47d7e3978f95d, "Evaluate: Propose Investments")
  }
  Strategy_ValueStream(e_id3db0cbb3835a52, "IT4IT: Integrate") {
    Strategy_ValueStream(e_id05a09249ecd25e, "Integrate: Plan Product Release")
    Strategy_ValueStream(e_id4d232b4e4d9151, "Integrate: Design & Develop")
    Strategy_ValueStream(e_id0925fc6db80453, "Integrate: Build, Integrate, & Test")
    Strategy_ValueStream(e_id6e0b4917897f59, "Integrate: Accept & Publish Release")
  }
  Strategy_ValueStream(e_id2a9a1fcfef0e5f, "IT4IT: Deploy") {
    Strategy_ValueStream(e_id8a5fa5c4e9f35c, "Deploy: Plan & Approve Deployment")
    Strategy_ValueStream(e_id409cff1ce21453, "Deploy: Fulfill Deployment")
    Strategy_ValueStream(e_id890c954b99ef59, "Deploy: Observe Deployment")
    Strategy_ValueStream(e_id633614d2551b5e, "Deploy: Validate Deployment")
  }
  Strategy_ValueStream(e_id2450fe8b5d985b, "IT4IT: Release") {
    Strategy_ValueStream(e_id43cdfeb06e1b53, "Release: Define Service Offer")
    Strategy_ValueStream(e_idda5e39c5b86f5f, "Release: Implement Service Offer")
    Strategy_ValueStream(e_id7325bf4931935a, "Release: Publish Service Offer")
  }
  Strategy_ValueStream(e_idd9aa16f51da958, "IT4IT: Operate") {
    Strategy_ValueStream(e_id61e6c145346959, "Operate: Detect Issue")
    Strategy_ValueStream(e_id7fed31beba0b52, "Operate: Diagnose Issue")
    Strategy_ValueStream(e_id983000175eba5f, "Operate: Resolve Issue")
  }
  Strategy_ValueStream(e_idd3ec795635fd51, "IT4IT: Consume") {
    Strategy_ValueStream(e_id6034216de9d457, "Consume: Publish Service Status")
    Strategy_ValueStream(e_id960e39e570c95b, "Consume: Provide Service Support")
    Strategy_ValueStream(e_idb1e9e123fa665a, "Consume: Agree to Service Offer")
    Strategy_ValueStream(e_id651f82429d3d53, "Consume: Subscribe to Service Offer")
    Strategy_ValueStream(e_id447d4f6179dc5e, "Consume: Select an Offer")
  }
}
Motivation_Outcome(e_id98a0748d593250, "IT4IT: Digital Product")

Rel_Realization_Up(e_idf2e1bcaab0b050, e_id98a0748d593250, "")
Rel_Flow(e_id2450fe8b5d985b, e_idd3ec795635fd51, "")
Rel_Flow(e_id2a9a1fcfef0e5f, e_id587fca1cae9254, "")
Rel_Flow(e_idd3ec795635fd51, e_id587fca1cae9254, "")
Rel_Flow(e_id7fb8e4a3ead059, e_id3db0cbb3835a52, "")
Rel_Flow(e_id587fca1cae9254, e_idd3ec795635fd51, "")
Rel_Flow(e_id587fca1cae9254, e_id7fb8e4a3ead059, "")
Rel_Flow(e_id587fca1cae9254, e_idd9aa16f51da958, "")
Rel_Flow(e_idd9aa16f51da958, e_id587fca1cae9254, "")
Rel_Flow(e_id2a9a1fcfef0e5f, e_idd9aa16f51da958, "")
Rel_Flow(e_idd3ec795635fd51, e_idd9aa16f51da958, "")
Rel_Flow(e_id3db0cbb3835a52, e_id2a9a1fcfef0e5f, "")
Rel_Flow(e_id587fca1cae9254, e_id2450fe8b5d985b, "")
Rel_Flow(e_id2450fe8b5d985b, e_id587fca1cae9254, "")
Rel_Flow(e_id587fca1cae9254, e_id3db0cbb3835a52, "")
Rel_Flow(e_id3db0cbb3835a52, e_id2450fe8b5d985b, "")
Rel_Flow(e_id7fb8e4a3ead059, e_id587fca1cae9254, "")
Rel_Flow(e_id3db0cbb3835a52, e_id587fca1cae9254, "")
Rel_Flow(e_id587fca1cae9254, e_id2a9a1fcfef0e5f, "")

@enduml
